import { defineField, defineType } from 'sanity'
import { TfiTruck, TfiWorld, TfiNotepad } from 'react-icons/tfi'

// --- DE VOLLEDIGE WERELDLIJST ---
const allCountries = [
  { title: '🇦🇫 Afghanistan', value: 'AF' },
  { title: '🇦🇱 Albania', value: 'AL' },
  { title: '🇩🇿 Algeria', value: 'DZ' },
  { title: '🇦🇩 Andorra', value: 'AD' },
  { title: '🇦🇴 Angola', value: 'AO' },
  { title: '🇦🇷 Argentina', value: 'AR' },
  { title: '🇦🇲 Armenia', value: 'AM' },
  { title: '🇦🇺 Australia', value: 'AU' },
  { title: '🇦🇹 Austria', value: 'AT' },
  { title: '🇦🇿 Azerbaijan', value: 'AZ' },
  { title: '🇧🇸 Bahamas', value: 'BS' },
  { title: '🇧🇭 Bahrain', value: 'BH' },
  { title: '🇧🇩 Bangladesh', value: 'BD' },
  { title: '🇧🇧 Barbados', value: 'BB' },
  { title: '🇧🇾 Belarus', value: 'BY' },
  { title: '🇧🇪 Belgium', value: 'BE' },
  { title: '🇧🇿 Belize', value: 'BZ' },
  { title: '🇧🇯 Benin', value: 'BJ' },
  { title: '🇧🇹 Bhutan', value: 'BT' },
  { title: '🇧🇴 Bolivia', value: 'BO' },
  { title: '🇧🇦 Bosnia and Herzegovina', value: 'BA' },
  { title: '🇧🇼 Botswana', value: 'BW' },
  { title: '🇧🇷 Brazil', value: 'BR' },
  { title: '🇧🇳 Brunei Darussalam', value: 'BN' },
  { title: '🇧🇬 Bulgaria', value: 'BG' },
  { title: '🇧🇫 Burkina Faso', value: 'BF' },
  { title: '🇧🇮 Burundi', value: 'BI' },
  { title: '🇰🇭 Cambodia', value: 'KH' },
  { title: '🇨🇲 Cameroon', value: 'CM' },
  { title: '🇨🇦 Canada', value: 'CA' },
  { title: '🇨🇻 Cape Verde', value: 'CV' },
  { title: '🇨🇫 Central African Republic', value: 'CF' },
  { title: '🇹🇩 Chad', value: 'TD' },
  { title: '🇨🇱 Chile', value: 'CL' },
  { title: '🇨🇳 China', value: 'CN' },
  { title: '🇨🇴 Colombia', value: 'CO' },
  { title: '🇰🇲 Comoros', value: 'KM' },
  { title: '🇨🇬 Congo', value: 'CG' },
  { title: '🇨🇷 Costa Rica', value: 'CR' },
  { title: '🇭🇷 Croatia', value: 'HR' },
  { title: '🇨🇺 Cuba', value: 'CU' },
  { title: '🇨🇾 Cyprus', value: 'CY' },
  { title: '🇨🇿 Czech Republic', value: 'CZ' },
  { title: '🇩🇰 Denmark', value: 'DK' },
  { title: '🇩🇯 Djibouti', value: 'DJ' },
  { title: '🇩🇲 Dominica', value: 'DM' },
  { title: '🇩🇴 Dominican Republic', value: 'DO' },
  { title: '🇪🇨 Ecuador', value: 'EC' },
  { title: '🇪🇬 Egypt', value: 'EG' },
  { title: '🇸🇻 El Salvador', value: 'SV' },
  { title: '🇬🇶 Equatorial Guinea', value: 'GQ' },
  { title: '🇪🇷 Eritrea', value: 'ER' },
  { title: '🇪🇪 Estonia', value: 'EE' },
  { title: '🇪🇹 Ethiopia', value: 'ET' },
  { title: '🇫🇯 Fiji', value: 'FJ' },
  { title: '🇫🇮 Finland', value: 'FI' },
  { title: '🇫🇷 France', value: 'FR' },
  { title: '🇬🇦 Gabon', value: 'GA' },
  { title: '🇬🇲 Gambia', value: 'GM' },
  { title: '🇬🇪 Georgia', value: 'GE' },
  { title: '🇩🇪 Germany', value: 'DE' },
  { title: '🇬🇭 Ghana', value: 'GH' },
  { title: '🇬🇷 Greece', value: 'GR' },
  { title: '🇬🇩 Grenada', value: 'GD' },
  { title: '🇬🇹 Guatemala', value: 'GT' },
  { title: '🇬🇳 Guinea', value: 'GN' },
  { title: '🇬🇼 Guinea-Bissau', value: 'GW' },
  { title: '🇬🇾 Guyana', value: 'GY' },
  { title: '🇭🇹 Haiti', value: 'HT' },
  { title: '🇭🇳 Honduras', value: 'HN' },
  { title: '🇭🇰 Hong Kong', value: 'HK' },
  { title: '🇭🇺 Hungary', value: 'HU' },
  { title: '🇮🇸 Iceland', value: 'IS' },
  { title: '🇮🇳 India', value: 'IN' },
  { title: '🇮🇩 Indonesia', value: 'ID' },
  { title: '🇮🇷 Iran', value: 'IR' },
  { title: '🇮🇶 Iraq', value: 'IQ' },
  { title: '🇮🇪 Ireland', value: 'IE' },
  { title: '🇮🇱 Israel', value: 'IL' },
  { title: '🇮🇹 Italy', value: 'IT' },
  { title: '🇯🇲 Jamaica', value: 'JM' },
  { title: '🇯🇵 Japan', value: 'JP' },
  { title: '🇯🇴 Jordan', value: 'JO' },
  { title: '🇰🇿 Kazakhstan', value: 'KZ' },
  { title: '🇰🇪 Kenya', value: 'KE' },
  { title: '🇰🇮 Kiribati', value: 'KI' },
  { title: '🇰🇵 Korea, North', value: 'KP' },
  { title: '🇰🇷 Korea, South', value: 'KR' },
  { title: '🇰🇼 Kuwait', value: 'KW' },
  { title: '🇰🇬 Kyrgyzstan', value: 'KG' },
  { title: '🇱🇦 Laos', value: 'LA' },
  { title: '🇱🇻 Latvia', value: 'LV' },
  { title: '🇱🇧 Lebanon', value: 'LB' },
  { title: '🇱🇸 Lesotho', value: 'LS' },
  { title: '🇱🇷 Liberia', value: 'LR' },
  { title: '🇱🇾 Libya', value: 'LY' },
  { title: '🇱🇮 Liechtenstein', value: 'LI' },
  { title: '🇱🇹 Lithuania', value: 'LT' },
  { title: '🇱🇺 Luxembourg', value: 'LU' },
  { title: '🇲🇴 Macao', value: 'MO' },
  { title: '🇲🇰 Macedonia', value: 'MK' },
  { title: '🇲🇬 Madagascar', value: 'MG' },
  { title: '🇲🇼 Malawi', value: 'MW' },
  { title: '🇲🇾 Malaysia', value: 'MY' },
  { title: '🇲🇻 Maldives', value: 'MV' },
  { title: '🇲🇱 Mali', value: 'ML' },
  { title: '🇲🇹 Malta', value: 'MT' },
  { title: '🇲🇭 Marshall Islands', value: 'MH' },
  { title: '🇲🇷 Mauritania', value: 'MR' },
  { title: '🇲🇺 Mauritius', value: 'MU' },
  { title: '🇲🇽 Mexico', value: 'MX' },
  { title: '🇫🇲 Micronesia', value: 'FM' },
  { title: '🇲🇩 Moldova', value: 'MD' },
  { title: '🇲🇨 Monaco', value: 'MC' },
  { title: '🇲🇳 Mongolia', value: 'MN' },
  { title: '🇲🇪 Montenegro', value: 'ME' },
  { title: '🇲🇦 Morocco', value: 'MA' },
  { title: '🇲🇿 Mozambique', value: 'MZ' },
  { title: '🇲🇲 Myanmar', value: 'MM' },
  { title: '🇳🇦 Namibia', value: 'NA' },
  { title: '🇳🇷 Nauru', value: 'NR' },
  { title: '🇳🇵 Nepal', value: 'NP' },
  { title: '🇳🇱 Netherlands', value: 'NL' },
  { title: '🇳🇿 New Zealand', value: 'NZ' },
  { title: '🇳🇮 Nicaragua', value: 'NI' },
  { title: '🇳🇪 Niger', value: 'NE' },
  { title: '🇳🇬 Nigeria', value: 'NG' },
  { title: '🇳🇴 Norway', value: 'NO' },
  { title: '🇴🇲 Oman', value: 'OM' },
  { title: '🇵🇰 Pakistan', value: 'PK' },
  { title: '🇵🇼 Palau', value: 'PW' },
  { title: '🇵🇦 Panama', value: 'PA' },
  { title: '🇵🇬 Papua New Guinea', value: 'PG' },
  { title: '🇵🇾 Paraguay', value: 'PY' },
  { title: '🇵🇪 Peru', value: 'PE' },
  { title: '🇵🇭 Philippines', value: 'PH' },
  { title: '🇵🇱 Poland', value: 'PL' },
  { title: '🇵🇹 Portugal', value: 'PT' },
  { title: '🇶🇦 Qatar', value: 'QA' },
  { title: '🇷🇴 Romania', value: 'RO' },
  { title: '🇷🇺 Russian Federation', value: 'RU' },
  { title: '🇷🇼 Rwanda', value: 'RW' },
  { title: '🇰🇳 Saint Kitts and Nevis', value: 'KN' },
  { title: '🇱🇨 Saint Lucia', value: 'LC' },
  { title: '🇻🇨 Saint Vincent and the Grenadines', value: 'VC' },
  { title: '🇼🇸 Samoa', value: 'WS' },
  { title: '🇸🇲 San Marino', value: 'SM' },
  { title: '🇸🇹 Sao Tome and Principe', value: 'ST' },
  { title: '🇸🇦 Saudi Arabia', value: 'SA' },
  { title: '🇸🇳 Senegal', value: 'SN' },
  { title: '🇷🇸 Serbia', value: 'RS' },
  { title: '🇸🇨 Seychelles', value: 'SC' },
  { title: '🇸🇱 Sierra Leone', value: 'SL' },
  { title: '🇸🇬 Singapore', value: 'SG' },
  { title: '🇸🇰 Slovakia', value: 'SK' },
  { title: '🇸🇮 Slovenia', value: 'SI' },
  { title: '🇸🇧 Solomon Islands', value: 'SB' },
  { title: '🇸🇴 Somalia', value: 'SO' },
  { title: '🇿🇦 South Africa', value: 'ZA' },
  { title: '🇪🇸 Spain', value: 'ES' },
  { title: '🇱🇰 Sri Lanka', value: 'LK' },
  { title: '🇸🇩 Sudan', value: 'SD' },
  { title: '🇸🇷 Suriname', value: 'SR' },
  { title: '🇸🇿 Swaziland', value: 'SZ' },
  { title: '🇸🇪 Sweden', value: 'SE' },
  { title: '🇨🇭 Switzerland', value: 'CH' },
  { title: '🇸🇾 Syria', value: 'SY' },
  { title: '🇹🇼 Taiwan', value: 'TW' },
  { title: '🇹🇯 Tajikistan', value: 'TJ' },
  { title: '🇹🇿 Tanzania', value: 'TZ' },
  { title: '🇹🇭 Thailand', value: 'TH' },
  { title: '🇹🇱 Timor-Leste', value: 'TL' },
  { title: '🇹🇬 Togo', value: 'TG' },
  { title: '🇹🇴 Tonga', value: 'TO' },
  { title: '🇹🇹 Trinidad and Tobago', value: 'TT' },
  { title: '🇹🇳 Tunisia', value: 'TN' },
  { title: '🇹🇷 Turkey', value: 'TR' },
  { title: '🇹🇲 Turkmenistan', value: 'TM' },
  { title: '🇹🇻 Tuvalu', value: 'TV' },
  { title: '🇺🇬 Uganda', value: 'UG' },
  { title: '🇺🇦 Ukraine', value: 'UA' },
  { title: '🇦🇪 United Arab Emirates', value: 'AE' },
  { title: '🇬🇧 United Kingdom', value: 'GB' },
  { title: '🇺🇸 United States', value: 'US' },
  { title: '🇺🇾 Uruguay', value: 'UY' },
  { title: '🇺🇿 Uzbekistan', value: 'UZ' },
  { title: '🇻🇺 Vanuatu', value: 'VU' },
  { title: '🇻🇦 Vatican City', value: 'VA' },
  { title: '🇻🇪 Venezuela', value: 'VE' },
  { title: '🇻🇳 Vietnam', value: 'VN' },
  { title: '🇾🇪 Yemen', value: 'YE' },
  { title: '🇿🇲 Zambia', value: 'ZM' },
  { title: '🇿🇼 Zimbabwe', value: 'ZW' },
]

export const shippingZone = defineType({
  name: 'shippingZone',
  title: 'Shipping Zones',
  type: 'document',
  icon: TfiTruck,
  fields: [
    // --- 1. ZONE DEFINITIE ---
    defineField({
      name: 'name',
      title: 'Zone Name',
      description: 'E.g. "Netherlands", "EU Zone 1", "North America"',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),

    defineField({
      name: 'isGlobalFallback',
      title: 'Is "Rest of World" / Global Fallback?',
      description: 'Check this box to apply these rates to ALL countries NOT listed in other zones.',
      type: 'boolean',
      initialValue: false,
    }),
    
    // HIER IS DE LIJST NU GEKOPPELD
    defineField({
      name: 'countries',
      title: 'Countries in this Zone',
      description: 'Search and select countries from the list.',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: allCountries, // <--- De grote lijst van hierboven
        layout: 'tags'      // Zorgt voor mooie labels die je kunt aanklikken
      },
      hidden: ({ document }) => document?.isGlobalFallback === true,
    }),

    // --- 2. CONTRACT INFO ---
    defineField({
        name: 'logisticsInfo',
        title: 'Internal Logistics Info',
        type: 'object',
        icon: TfiNotepad,
        options: { collapsible: true, collapsed: true }, 
        fields: [
            defineField({
                name: 'courier',
                title: 'Primary Courier',
                type: 'string',
                options: {
                    list: ['PostNL', 'DHL Express', 'FedEx', 'UPS', 'Art Courier', 'Other']
                }
            }),
            defineField({
                name: 'contractNote',
                title: 'Contract / Update Note',
                description: 'E.g. "Prices per Jan 2026 (DHL Contract #1234)"',
                type: 'string',
            })
        ]
    }),

    // --- 3. DE TARIEVEN ---
    defineField({
      name: 'rates',
      title: 'Shipping Rates (EUR)',
      description: 'Vul hier de actuele prijzen in. Gebruik de tabel hieronder als spiekbriefje.',
      type: 'object',
      options: { collapsible: false },
      fields: [
        defineField({ 
            name: 'mailbox', 
            title: '✉️ Brievenbuspakket (≤ 3.8cm)', 
            description: 'Richtprijs: NL ~€4 | EU ~€10 | World ~€25',
            type: 'number', 
            validation: (Rule) => Rule.required().min(0)
        }),
        defineField({ 
            name: 'parcel_standard', 
            title: '📦 Standard Parcel (approx 45x60cm)', 
            description: 'Richtprijs: NL ~€15 | EU ~€30 | World ~€80',
            type: 'number', 
            validation: (Rule) => Rule.required().min(0)
        }),
        defineField({ 
            name: 'parcel_large', 
            title: '📦 Large Parcel (approx 90x120cm)', 
            description: 'Richtprijs: NL ~€40 | EU ~€90 | World ~€200',
            type: 'number', 
            validation: (Rule) => Rule.required().min(0)
        }),
        defineField({ 
            name: 'freight', 
            title: '🚚 Crated Freight (Oversized/Pallet)', 
            description: 'Richtprijs: NL ~€250 | EU ~€400 | World ~€500+',
            type: 'number', 
            validation: (Rule) => Rule.required().min(0)
        }),
      ]
    }),
  ],
  preview: {
    select: {
      title: 'name',
      countries: 'countries',
      isGlobal: 'isGlobalFallback',
      courier: 'logisticsInfo.courier'
    },
    prepare({ title, countries, isGlobal, courier }) {
      if (isGlobal) {
        return {
            title: `🌍 ${title} (Global Fallback)`,
            subtitle: courier ? `Via ${courier}` : 'Standard rates',
            media: TfiWorld
        }
      }

      const count = countries ? countries.length : 0;
      const subtitle = count > 0 
        ? `${count} countries (${courier || 'No courier'})` 
        : 'No countries assigned';
      
      return {
        title: title,
        subtitle: subtitle,
        media: TfiTruck
      }
    }
  }
})
